# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Cortico Blog
email: help@cortico.ca
description: > # this means to ignore newlines until "baseurl:"
  Cortico software is designed for physicians & clinic managers to eliminate overhead
  and reduce in-clinic wait times. Our blog focuses on relevant content, especially telehealth & EMR.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://cortico.ca" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  countable-web

# Build settings
markdown: kramdown
